steps:
  # 构建后端镜像
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/alphaseek-backend'
      - '--file=docker/Dockerfile.backend'
      - '.'

  # 构建前端镜像
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/alphaseek-frontend'
      - '--file=docker/Dockerfile.frontend'
      - '--build-arg=VUE_APP_API_BASE_URL=https://alphaseek-backend-2fff5k3ydq-uc.a.run.app'
      - '--build-arg=VUE_APP_WS_BASE_URL=wss://alphaseek-backend-2fff5k3ydq-uc.a.run.app'
      - '.'

  # 推送后端镜像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args: ['push', 'gcr.io/$PROJECT_ID/alphaseek-backend']

  # 推送前端镜像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args: ['push', 'gcr.io/$PROJECT_ID/alphaseek-frontend']

  # 部署后端到 Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-backend'
    args:
      - 'run'
      - 'deploy'
      - 'alphaseek-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/alphaseek-backend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=FRONTEND_URLS=https://alphaseek-frontend-2fff5k3ydq-uc.a.run.app'
      - '--set-env-vars=CLOUD_RUN_WEBSOCKET=true'
      - '--timeout=3600'
      - '--concurrency=80'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--session-affinity'

  # 部署前端到 Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-frontend'
    args:
      - 'run'
      - 'deploy'
      - 'alphaseek-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/alphaseek-frontend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/alphaseek-backend'
  - 'gcr.io/$PROJECT_ID/alphaseek-frontend'