version: '3.8'

services:
  backend:
    build: 
      context: ../backend
      dockerfile: ../docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - influxdb

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=memeorg
      - DOCKER_INFLUXDB_INIT_BUCKET=meme_coin_data
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data: 