version: '3.8'

services:
  backend:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - API_BASE_URL=http://localhost:8000
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - FRONTEND_URLS=http://localhost:8080,https://alphaseek-frontend-1042424702662.us-central1.run.app

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8000
      - VUE_APP_WS_BASE_URL=ws://localhost:8000
# volumes:
  # 如果不再需要 influxdb-data 卷，也可以移除
  # influxdb-data: 
