# 构建阶段
FROM node:16-alpine AS build-stage

WORKDIR /frontend

# 复制 package.json 和 package-lock.json
COPY frontend/package*.json ./

# 安装依赖
RUN npm install

# 复制项目文件
COPY frontend/ .

# 构建生产版本
RUN npm run build


# 生产阶段
FROM nginx:stable-alpine AS production-stage

# 从构建阶段复制构建结果到 nginx 目录
COPY --from=build-stage /frontend/dist /usr/share/nginx/html

# 复制自定义 nginx 配置
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# 暴露端口
EXPOSE 80

# 启动 nginx
CMD ["nginx", "-g", "daemon off;"] 